users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ubah_data_user/', views.UserEditView.as_view(), name='ubah_data_user'),
    path('signup/', views.UserRegisterView.as_view(), name='register'),
    path('password/', views.PasswordChangeView.as_view(), name='ubah_password'),   
]

webfisika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexHomeView.as_view(), name='home'),
    # path('', views.ComingSoon.as_view(), name='home'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('success/', views.Success.as_view(), name = 'success'),
    path('penilaian/', include(('penilaian.urls', 'penilaian'), namespace='penilaian')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/comingsoon.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Coming Soon!</title>
        <link rel="icon" type="image/x-icon" href="/assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&amp;display=swap" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/assets/css/comingsoon.css" rel="stylesheet" />
    </head>
    <body>
        <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop"><source src="/assets/mp4/bg.mp4" type="video/mp4" /></video>
        <!-- Masthead-->
        <div class="masthead">
            <div class="masthead-content text-white">
                <div class="container-fluid px-4 px-lg-0">
                    <h1 class="fst-italic lh-1 mb-4">Our Website is Under Construction</h1>
                    <p class="mb-5">We're working hard to finish the development of this site. Can't wait to see you soon!</p>
                    <br>
                    <h3><img style="width: 50px;" src="/assets/img/logo-unpad1.png" alt="">Departemen Fisika FMIPA Unpad</h3>
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Selamat Datang!</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  {% include 'snippets/style.html' %}
</head>

<body>
  {% include 'snippets/navbar.html' %}
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
          <h1>Aplikasi Penilaian Karya Ilmiah</h1>
          <h2>Departemen Fisika FMIPA Universitas Padjadjaran</h2>
          <div class="d-lg-flex">
            <!-- <a href="#about" class="btn-get-started scrollto">About Us</a> -->
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
          <img src="/assets/img/hero-img.png" class="img-fluid animated" alt="">
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Us Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Tentang Aplikasi</h2>
        </div>

        <div class="row content">
          <div class="col-md-6 d-flex justify-content-center">
            <img style="width: 450px; height: 250px;" src="/assets/img/coba.png" alt="">
          </div>
          <div class="col-md-6 pt-4 pt-lg-0">
            <p class="d-flex justify-content-center">
              Aplikasi Penilaian Karya Ilmiah Departemen Fisika FMIPA Universitas Padjadjaran ini ini adalah aplikasi yang digunakan untuk mempermudah proses penilaian karya ilmiah dosen. 
              Dengan adanya aplikasi ini, diharapkan penilaian karya ilmiah dapat dilakukan secara objektif dan efisien.
            </p>
            <br>
            <a href="https://phys.unpad.ac.id/program-2/sarjana" target="_blank" class="btn-learn-more">Web Fisika</a>
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top" data-aos="fade-up">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Departemen Fisika</h3>
            <p>Universitas Padjadjaran</p>
            <p>Kampus Jatinangor</p>
            <p>Jln. Raya Bandung-Sumedang Km. 21</p>
            <p>Jatinangor, Kab. Sumedang 45363</p>
            <p>Jawa Barat</p> <br>
            <p><strong>Telepon:</strong> (022) 779 6014</p>
            <p><strong>Email:</strong> kadep@phys.unpad.ac.id</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Tautan Penting</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="https://siat.unpad.ac.id/index.php/login">SIAT Unpad</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="https://phys.unpad.ac.id/">Website Fisika Unpad</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="http://ika-fisika.or.id/">Website IKA Fisika Unpad</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'admin:index' %}">Admin Site</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Temukan Kami!</h3>
            <iframe class="maps" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.691078373772!2d107.77145831421167!3d-6.927480569731207!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e68c4ae73e42ed3%3A0x547bfec4d2c2ff32!2sDepartemen%20Fisika%20FMIPA%20Unpad!5e0!3m2!1sen!2sid!4v1616595306914!5m2!1sen!2sid" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-bg">
      <div class="container footer-bottom clearfix">
        <div class="copyright">
          &copy; Copyright <strong><span>Departemen Fisika</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
  <div id="preloader"></div>

  {% include 'snippets/script.html' %}

</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% include 'snippets/style.html' %}
</head>
<body>
    {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio login">
        <br>
        <div class="section-title" data-aos="zoom-in">
            <h2 class="text-white">Login Site</h2>
        </div>
        <div class="container d-flex justify-content-center" data-aos="zoom-in">
            <div class="card">
                <article class="card-body">
                <a href="{% url 'users:register' %}" class="float-right btn btn-outline-warning">Register</a>
                <h4 class="card-title mb-4 mt-1">Sign in</h4>
                <form method="POST">
                    {% csrf_token %}
                    {% for message in messages %}
                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>
                        {{ message }}
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <label>Nomor Induk Pegawai :</label>
                        <input type="text" name="username" id="username" class="form-control" placeholder="NIP">
                    </div> <!-- form-group// -->
                    <div class="form-group">
                        <label>Password :</label>
                        <input name="password" id="password" class="form-control" placeholder="Password" type="password">
                    </div> <!-- form-group// -->
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{request.GET.next}}">
                    {% endif %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login </button>
                    </div> <!-- form-group// -->                                                           
                </form>
                </article>
            </div>
        </div>
    </section>

    {% include 'snippets/script.html' %}
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
    {% include 'snippets/style.html' %}
</head>
<body>
    <div class="jumbotron text-center">
        <h1 class="display-3">Apakah anda yakin ingin logout?</h1>
        <p class="lead">Jika ya, klik tombol logout. Jika tidak, klik tombol cancel</p>
        <hr>
        <br>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <input type="submit" class="btn btn-danger" id="logout" name="logout" value="Logout">
                </div>
                <div class="col-md-6">
                    <input type="submit" class="btn btn-warning" id="logout" name="logout" value="Cancel">
                </div>
            </div>
            <!-- <button type="submit">Logout</button> -->
        </form>
      </div>

    {% include 'snippets/script.html' %}
</body>
</html>

templates/success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>We received your file;<br/> we'll be in touch shortly!</p>
        <a href="{% url 'home' %}" class="btn btn-info" role="button">Back to home</a>
      </div>
    </body>
</html>